### ISSUE TITLE
Error in list[G_lineages], object 'G_lineages' not found

### ISSUE THREAD

**Issue by GreyPEK** [caijun/pMCMC-SIR#1]
Sorry to bother you, and it is a long time ago project. I sincerely express my best wishes to you and my deepest admiration for your remarkable work in this area. But I have this problem while trying to run your code, could you please give me some advice? Thank you!
```
list[G_lineages, G_coal_event, G_lineages_dt, G_indices, G_dt_ref, event_times] <- get_G_events(MCMC_params, sample_times, sample_sizes, coal_times, obsv_times)

Error in list[G_lineages, G_coal_event, G_lineages_dt, G_indices, G_dt_ref,  : 
  object 'G_lineages' not found
In addition: Warning message:
In (0L:n) * by :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.
```

**Comment by caijun** [comment]
Thanks for your interest in this repo. I have updated the file structures and now you can run the code by following the intructions in README. If you have further questions on infecctious disease modelling, feel free to contact me via email.

**Comment by GreyPEK** [comment]
Thank you very much for providing the new version! However, it seems that I am still encountering some problems. Which version of R are you using? I tried both 4.2.3 and 4.0.5 but couldn't load the 'TTmisc' package.
```
install.packages('TTmisc')
Warning in install.packages :
  package ‘TTmisc’ is not available for this version of R
```
And there is error:
```
list[] <- readMat("/pMCMC-SIR-master/pMCMCSourceCode/SIR_endemic_sim3_mockData.mat", fixNames = F)
Error in list[] <- readMat("/pMCMC-SIR-master/pMCMCSourceCode/SIR_endemic_sim3_mockData.mat",  : 
  object of type 'builtin' is not subsettable
```
```
list[G_lineages, G_coal_event, G_lineages_dt, G_indices, G_dt_ref, event_times] <- get_G_events(MCMC_params, sample_times, sample_sizes, coal_times, obsv_times)
Error in list[G_lineages, G_coal_event, G_lineages_dt, G_indices, G_dt_ref,  : 
  object 'G_lineages' not found
In addition: Warning message:
In (0L:n) * by :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.
```

**Comment by caijun** [comment]
The `TTmisc` package is developed by me and only available on [my github](https://github.com/caijun/TTmisc). You can install it following the instruction. If your R cannot connect to github, you can download the package and install it locally.  The error can be resolved after successfullt installing `TTmisc` package.

**Comment by GreyPEK** [comment]
The code has no errors now, thank you for your guidance!
